# Generated by Django 5.0.4 on 2024-05-23 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardstash', '0002_alter_cardstash_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocale',
            fields=[
                ('cardstash_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardstash.cardstash')),
                ('description', models.TextField()),
            ],
            bases=('cardstash.cardstash',),
        ),
    ]
