# Generated by Django 5.0.4 on 2024-05-23 20:23

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0015_drop_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_card_in_stash', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardStash',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='A memorable name for the deck.', max_length=80)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date created')),
                ('modified', models.DateTimeField(default=datetime.datetime.now, verbose_name='date modified')),
                ('card_allocation', models.ManyToManyField(through='cardstash.CardAllocation', to='decks.card')),
            ],
        ),
        migrations.AddField(
            model_name='cardallocation',
            name='stash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardstash.cardstash'),
        ),
        migrations.AddConstraint(
            model_name='cardallocation',
            constraint=models.UniqueConstraint(fields=('stash_id', 'card_id'), name='unique_stash_entries'),
        ),
    ]
