# Generated by Django 5.0.4 on 2024-05-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardstash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstash',
            name='name',
            field=models.CharField(help_text='A memorable name.', max_length=80),
        ),
    ]
