# Generated by Django 5.0.4 on 2024-06-03 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardstash', '0002_alter_cardstash_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstash',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='cardstash',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified'),
        ),
    ]
