# Generated by Django 5.0.4 on 2024-05-08 17:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=64)),
                ('super_type', models.CharField(max_length=15)),
                ('subtypes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('hp', models.PositiveIntegerField()),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('regulation_mark', models.CharField(max_length=4)),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('expanded_legal', models.BooleanField()),
                ('standard_legal', models.BooleanField()),
                ('unlimited_legal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deck_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('deck_name', models.CharField(max_length=80)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('game_format', models.CharField(choices=[('STD', 'Standard'), ('EXP', 'Expanded'), ('GLC', 'Gym Leader Challenge'), ('UNL', 'Unlimited')], max_length=10)),
                ('card_list', models.ManyToManyField(related_name='deck_id', to='decks.card')),
            ],
        ),
    ]
