# Generated by Django 5.0.4 on 2024-06-03 20:08

import datetime
import django.contrib.postgres.fields
import django.db.migrations.operations.special
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('decks', '0001_initial'), ('decks', '0002_decks_uuid'), ('decks', '0003_populate_uuid_values'), ('decks', '0004_enforce_unique_uuid'), ('decks', '0005_switch_to_uuid'), ('decks', '0006_alter_deck_deck_name_alter_deck_game_format'), ('decks', '0007_remove_deck_card_list_deck_new_card_list'), ('decks', '0008_remove_deck_new_card_list_deck_card_list'), ('decks', '0009_cardallocation'), ('decks', '0011_remove_deck_card_list_deck_card_allocation'), ('decks', '0012_rename_card_id_cardallocation_card_and_more'), ('decks', '0013_deck_is_stash_deck_modified'), ('decks', '0014_rename_deck_name_deck_name_and_more'), ('decks', '0015_drop_tables')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=64)),
                ('super_type', models.CharField(max_length=15)),
                ('subtypes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('hp', models.PositiveIntegerField()),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('regulation_mark', models.CharField(max_length=4)),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('expanded_legal', models.BooleanField()),
                ('standard_legal', models.BooleanField()),
                ('unlimited_legal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deck_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('deck_name', models.CharField(max_length=80)),
                # Causes warnings despite 0015 deleting the whole model
                #('created', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date created')),
                ('game_format', models.CharField(choices=[('STD', 'Standard'), ('EXP', 'Expanded'), ('GLC', 'Gym Leader Challenge'), ('UNL', 'Unlimited')], max_length=10)),
                ('card_list', models.ManyToManyField(related_name='deck_id', to='decks.card')),
                ('deck_uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deck',
            name='deck_id',
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_name',
            field=models.CharField(help_text='A memorable name for the deck.', max_length=80),
        ),
        migrations.AlterField(
            model_name='deck',
            name='game_format',
            field=models.CharField(choices=[('STD', 'Standard'), ('EXP', 'Expanded'), ('GLC', 'Gym Leader Challenge'), ('UNL', 'Unlimited')], help_text='The format this deck is legal in.', max_length=10),
        ),
        migrations.RemoveField(
            model_name='deck',
            name='card_list',
        ),
        migrations.CreateModel(
            name='CardAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_card_in_deck', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.deck')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='card_allocation',
            field=models.ManyToManyField(through='decks.CardAllocation', to='decks.card'),
        ),
        migrations.AddConstraint(
            model_name='cardallocation',
            constraint=models.UniqueConstraint(fields=('deck_id', 'card_id'), name='unique_deck_entries'),
        ),
        # Causes warnings
        #migrations.AddField(
        #    model_name='deck',
        #    name='modified',
        #    field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date modified'),
        #),
        migrations.RenameField(
            model_name='deck',
            old_name='deck_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='deck_uuid',
            new_name='uuid',
        ),
        migrations.DeleteModel(
            name='deck',
        ),
    ]
