# Generated by Django 5.0.4 on 2024-05-13 19:23

from django.db import migrations
import uuid


def gen_uuid( apps, schema_editor ):
    deck_model = apps.get_model( "decks", "Deck" )
    for row in deck_model.objects.all():
        row.deck_uuid = uuid.uuid4()
        row.save( update_fields = ["deck_uuid"] )

class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_decks_uuid'),
    ]

    operations = [
            migrations.RunPython( gen_uuid, reverse_code=migrations.RunPython.noop )
    ]
