# Generated by Django 5.0.4 on 2024-05-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_alter_deck_deck_name_alter_deck_game_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='card_list',
        ),
        migrations.AddField(
            model_name='deck',
            name='new_card_list',
            field=models.ManyToManyField(related_name='deck_uuid', to='decks.card'),
        ),
    ]
