# Generated by Django 5.0.4 on 2024-05-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_remove_deck_card_list_deck_new_card_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='new_card_list',
        ),
        migrations.AddField(
            model_name='deck',
            name='card_list',
            field=models.ManyToManyField(related_name='deck_uuid', to='decks.card'),
        ),
    ]
