# Generated by Django 5.0.4 on 2024-05-16 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_remove_deck_new_card_list_deck_card_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_card_in_deck', models.PositiveIntegerField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.card')),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.deck')),
            ],
        ),
    ]
