# Generated by Django 5.0.4 on 2024-05-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0009_cardallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='card_list',
        ),
        migrations.AddField(
            model_name='deck',
            name='card_allocation',
            field=models.ManyToManyField(through='decks.CardAllocation', to='decks.card'),
        ),
    ]
