# Generated by Django 5.0.4 on 2024-05-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0013_deck_is_stash_deck_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='deck_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='deck_uuid',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='is_stash',
        ),
    ]
