# Generated by Django 5.0.4 on 2024-05-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0014_rename_deck_name_deck_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='deck'),
    ]
