# Generated by Django 5.0.4 on 2024-05-23 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardstash', '0001_initial'),
        ('decks', '0015_drop_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('cardstash_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardstash.cardstash')),
                ('game_format', models.CharField(choices=[('STD', 'Standard'), ('EXP', 'Expanded'), ('GLC', 'Gym Leader Challenge'), ('UNL', 'Unlimited')], help_text='The format this deck is legal in.', max_length=10)),
            ],
            bases=('cardstash.cardstash',),
        ),
        migrations.DeleteModel(
            name='CardAllocation',
        ),
    ]
